### PR TITLE
Add env var to enable oaipmh scraper

### LINKED ISSUE #103: Add new environment variable ENABLE_OAIPMH_SCRAPER
There exists a new environment variable `ENABLE_OAIPMH_SCRAPER`, see [here](https://github.com/research-software-directory/RSD-as-a-service/blob/6299b419146ecc7a346e35ebc88b5b768357d89e/.env.example#L119).

### PR DESCRIPTION
**Pull request by Normo**
* Closes #103

### CODE REVIEW

**Review by tobiashuste — DISMISSED** [review]
Thanks, @Normo. This looks good to me :shipit:

**Comment by Normo** [comment]
Dear @tobiashuste, the Nginx config template still had to be updated. Could you please review it again?

**Comment by Normo** [comment]
@christianhueserhzdr Could you please review this PR?

**Review by christianhueserhzdr — APPROVED** [review]
Dear Norman @Normo, thanks, I am fine with the addition of the env var and NGINX configuration. I'll approve and merge this MR now.

**Pull request merged**
